# ==========================================
# DEPLOYMENT DEL FRONTEND
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-despacho
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 637423587001.dkr.ecr.us-east-1.amazonaws.com/innovatech-frontend:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20

---
# ==========================================
# SERVICIO: EXPOSICIÓN A INTERNET
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend
